export class OptionalStockViewModel {
  /**
   * 自选股首页列表，模拟数据
   */
  opTestDataList: OpListDataBean[] = [
    { stockCode: "600010", stockName: "包钢股份", newPrice: "1.54", priceRange: "+0.65%" },
    { stockCode: "600519", stockName: "贵州茅台", newPrice: "1692.33", priceRange: "-1.29%" },
    { stockCode: "600007", stockName: "中国国贸", newPrice: "18.33", priceRange: "-0.29%" },
    { stockCode: "600010", stockName: "包钢股份", newPrice: "1.54", priceRange: "+0.65%" },
    { stockCode: "600519", stockName: "贵州茅台", newPrice: "1692.33", priceRange: "-1.29%" },
    { stockCode: "600007", stockName: "中国国贸", newPrice: "18.33", priceRange: "-0.29%" },
    { stockCode: "600010", stockName: "包钢股份", newPrice: "1.54", priceRange: "+0.65%" },
    { stockCode: "600519", stockName: "贵州茅台", newPrice: "1692.33", priceRange: "-1.29%" },
    { stockCode: "600007", stockName: "中国国贸", newPrice: "18.33", priceRange: "-0.29%" },
    { stockCode: "600010", stockName: "包钢股份", newPrice: "1.54", priceRange: "+0.65%" },
    { stockCode: "600519", stockName: "贵州茅台", newPrice: "1692.33", priceRange: "-1.29%" },
    { stockCode: "600007", stockName: "中国国贸", newPrice: "18.33", priceRange: "-0.29%" },
    { stockCode: "600010", stockName: "包钢股份", newPrice: "1.54", priceRange: "+0.65%" },
    { stockCode: "600519", stockName: "贵州茅台", newPrice: "1692.33", priceRange: "-1.29%" },
    { stockCode: "600007", stockName: "中国国贸", newPrice: "18.33", priceRange: "-0.29%" },
    { stockCode: "600010", stockName: "包钢股份", newPrice: "1.54", priceRange: "+0.65%" },
    { stockCode: "600519", stockName: "贵州茅台", newPrice: "1692.33", priceRange: "-1.29%" },
    { stockCode: "600007", stockName: "中国国贸", newPrice: "18.33", priceRange: "-0.29%" },
    { stockCode: "600010", stockName: "包钢股份", newPrice: "1.54", priceRange: "+0.65%" },
    { stockCode: "600519", stockName: "贵州茅台", newPrice: "1692.33", priceRange: "-1.29%" },
    { stockCode: "600007", stockName: "中国国贸", newPrice: "18.33", priceRange: "-0.29%" },
  ]
}

export class OpListDataBean {
  stockCode: string = ""
  stockName: string = ""
  newPrice: string = ""
  priceRange: string = ""
}